### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by clarkwinkelmann** [flagrow/mason#1]
Before it goes live

**Comment by luceos** [comment]
- [x] use placeholders instead of "New value" value for field names 
![image](https://user-images.githubusercontent.com/504687/31197839-adf9c792-a952-11e7-84e2-ccc5668c4175.png)
- [ ] I'd make the frontend part closed, unless fields are required. Otherwise it's taking far too much space?
- [x] Click to edit field should not show up on the button to add new fields
![image](https://user-images.githubusercontent.com/504687/31197982-2d4e56b6-a953-11e7-85c8-acc62aae484c.png)
- [x] Field answers in admin should have a dotted border, I thought that was the input
![image](https://user-images.githubusercontent.com/504687/31198045-41f8814a-a953-11e7-8975-69c42ecac2dc.png)
- [x] Admin nav icon has wrong icon.
- [ ] Speaking of icon, the package icon needs to be replaced but I haven't seen a better alternative in font awesome.

**Comment by luceos** [comment]
In https://github.com/flagrow/mason/blob/master/src/Listeners/AddApiRoutes.php

import the Controllers namespace then prefix all controllers with Controllers in the route definition. Looks much cleaner and is almost equally easy to read. Maybe put the route definitions in multiple lines instead of one.

**Comment by clarkwinkelmann** [comment]
Note to self: rename route names to use mason instead of discussion-fields

**Comment by luceos** [comment]
Going to de-assign this from me @clarkwinkelmann .

**Comment by clarkwinkelmann** [comment]
I'll close this. Everything that required immediate change has been done and it's been live for some time now.
